export const FETCH_BOOKS_PAGE_STARTED = "FETCH_BOOKS_PAGE_STARTED";
export const FETCH_BOOKS_PAGE_END = "FETCH_BOOKS_PAGE_END";
export const FETCH_BOOKS_PAGE_STATUS_END = "FETCH_BOOKS_PAGE_STATUS_END";
